from abc import ABC, abstractmethod
from app.adapters.base import BotHealth
class BotProcessManager(ABC):
    """Concurrency-safe process boundary; implementations must prevent duplicate processes."""
    @abstractmethod
    async def get_status(self,bot_id:str)->BotHealth: ...
    @abstractmethod
    async def start_bot(self,bot_id:str)->None: ...
    @abstractmethod
    async def stop_bot(self,bot_id:str)->None: ...
    @abstractmethod
    async def restart_bot(self,bot_id:str)->None: ...
